# Generated by Django 4.0.3 on 2022-03-11 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tyre',
            old_name='degration',
            new_name='degradation',
        ),
    ]
